Feasablty study/Controllers/Support_MessagesController.cs
using Feasablty_study.Infrastructure.Data;
using Feasablty_study.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Feasablty_study.Infrastructure.Repository;
using Microsoft.AspNetCore.Identity;
using System.Security.Claims;

namespace Feasablty_study.Controllers
{
    [Authorize]
    public class Support_MessagesController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly ISupportMessageRepo _messageRepo;

        public Support_MessagesController(ISupportMessageRepo messageRepo,UserManager<User> userManager)
        {
            _userManager = userManager;
            _messageRepo = messageRepo;

        }
        [Authorize(Roles ="Admin")]
        // GET: Support_Messages
        public async Task<IActionResult> Index()
        {
            var AllMessages = await _messageRepo.GetAllAsync(s=>s.User);  //_messageRepo.GetAllAsync();

            return View(AllMessages.ToList());
        }
        [Authorize(Roles = "Admin")]
        // GET: Support_Messages/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var support_Messages = await _messageRepo.GetByIdAsync((int)id,s=>s.User);
                
            if (support_Messages == null)
            {
                return NotFound();
            }

            return View(support_Messages);
        }

        // GET: Support_Messages/Create
        public IActionResult Create()
        {
            return View();
        }

  
        [HttpPost]
        public async Task<IActionResult> Create([Bind("Id,Title,Content,Email,Date,UserId")] Support_Messages support_Messages)
        {
            if (ModelState.IsValid)
            {
                support_Messages.UserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                support_Messages.User = await _userManager.Users.FirstOrDefaultAsync(u=>u.Id==support_Messages.UserId);
                await _messageRepo.AddAsync(support_Messages);
                return RedirectToAction("Index", "Home");
            }
            return View(support_Messages);
        }

        [Authorize(Roles = "Admin")]
        // GET: Support_Messages/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var support_Messages = await _messageRepo.GetByIdAsync((int)id, s => s.User);
             
            if (support_Messages == null)
            {
                return NotFound();
            }

            return View(support_Messages);
        }
        [Authorize(Roles = "Admin")]
        // POST: Support_Messages/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
             await _messageRepo.DeleteAsync(id);
            return RedirectToAction("Index");
        }

    }
}

Feasablty study/Views/Support_Messages/Create.cshtml
@model Feasablty_study.Models.Support_Messages

<div class="authentication-wrapper authentication-basic container-p-y">
        <div class="authentication-inner py-4">
          <!-- Register -->
          <div class="card">
            <div class="card-body">
              <!-- Logo -->
              <div class="app-brand justify-content-center">
                <a href="dashboards-analytics - Copy.html" class="app-brand-link gap-2">
                  <span class="app-brand-logo demo">
                    <svg width="26px" height="26px" viewBox="0 0 26 26" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                      <title>icon</title>
                    
                    </svg>
                  </span>
                  <span class="app-brand-text demo h3 fw-bold mb-0">تواصل بالدعم الفني  </span>
                </a>
              </div>
              <!-- /Logo -->
              <h4 class="mb-2"> اكتب رسالتك في الاسفل " 👇"</h4>
             

              <form id="formAuthentication" class="mb-3 fv-plugins-bootstrap5 fv-plugins-framework" asp-action="Create" method="POST">
                   <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                   <div class="form-group">
                      <label for="Email" class="form-label"></label>
                      <input type="text" class="form-control" id="Email" name="Email" placeholder="  البريد الخاص بالمرسل " autofocus="" asp-for="Email">
                      <span asp-validation-for="Email" class="text-danger"></span>
                  </div>
                <div class="form-title-toggle mb-3">
                  <div class="form-group">
                      <label for="Title" class="form-label"></label>
                      <input class="form-control" type="text" name="title" placeholder="عنوان الرسالة" asp-for="Title"> 
                        <span asp-validation-for="Title" class="text-danger"></span>    
                  </div>

                </div>
                <div class="mb-3">
                 <div class="form-group">
                     <label for="Content" class="form-label" >محتوى الرسالة </label>

                     @Html.TextAreaFor(a=>a.Content,new {@class = "form-control" })
                    <span asp-validation-for="Content" class="text-danger"></span>

                 </div>
                </div>
                <div class="mb-3">
                  <input class="btn btn-primary d-grid w-100" type="submit" value="إرسال" />

                </div>
              
            </form>
            </div>
            
          </div>
          
        </div>
        
      </div>
      <div class="d-flex col-12 justify-content-between">
          
              <button class="btn btn-primary btn-prev" onclick="location.href='@Url.Action("Index", "Support_Messages")'"  >
                <i class="bx bx-chevron-left bx-sm ms-sm-n2"></i>
                <span class="d-none d-sm-inline-block">رجوع</span>
              </button> 

       </div>





@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Feasablty study/Views/Support_Messages/Index.cshtml
@model IEnumerable<Feasablty_study.Models.Support_Messages>

    @{
    ViewData["Title"] = "عرض الرسائل";
   
}


    <link rel="stylesheet" href="~/assets/vendor/libs/typeahead-js/typeahead.css" />
    <link rel="stylesheet" href="~/assets/vendor/libs/shepherd/shepherd.css" />
<div class="card">
    <h4 class="card-header"> الرسائل</h4>
    <div class="card-body">
                <meta name="viewport" content="width=device-width" />
            <table id="dataTable" class="table table-hover">
                     <thead>
                         <tr>
                        <th> تسلسل </th>
                        <th>البريد الالكتروني</th>
                        <th> تاريخ الارسال</th>
                        <th>اسم المرسل</th>
                        <th>  الاجراءات</th> 
                       </tr>
                  </thead>

                <tbody>
                    @if (Model.Count() == 0)
                    {
                        <tr>
                            <td colspan="3" style="color:red">
                                لا يوجد نتائج
                            </td>
                        </tr>
                    }
                    else
                    {
                        @foreach (var item in Model)
                        {
                             var TargetId="modalN"+@item.Id;

                            <tr>
                                 
                                  <td data-title=" تسلسل:">@Html.DisplayFor(modelItem => item.Id)</td>
                                <td data-title=" البريد الالكتروني:">@Html.DisplayFor(modelItem => item.Email) </td>
                                <td data-title=" تاريخ الارسال:"> @Html.DisplayFor(modelItem => item.Date)</td>
                                <td data-title=" اسم المرسل:"> @Html.DisplayFor(modelItem => item.User.Name)</td>
                                
                            <td data-title="الاجراءات">
                           
                                         <!-- Modal -->
                    <!-- Modal -->
                       <div class="demo-inline-spacing">
                        <!-- Button trigger modal -->
                        <button
                          type="button"
                          class="btn btn-secondary"
                          data-bs-toggle="modal"
                          data-bs-target="#@TargetId"
                        >
                         <i> عرض الرسالة</i>
                        </button>
                      </div>
                       </td>
                      
                     </tr>
                      <div class="modal fade" id=@TargetId tabindex="-1" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-scrollable" role="document">
                          <div class="modal-content">
                            <div class="modal-header">
                              <h5 class="modal-title" id="modalScrollableTitle"> @Html.DisplayFor(modelItem => item.Title)</h5>
                              <button
                                type="button"
                                class="btn-close"
                                data-bs-dismiss="modal"
                                aria-label="Close"
                              ></button>
                            </div>
                            <div class="modal-body"
                               asp-route-id="@item.Id">
                              <p>
                               @Html.DisplayFor(modelItem => item.Content)
                              </p>
                              
                            </div>
                            <div class="modal-footer">
                              <button type="button" class="btn btn-label-secondary" data-bs-dismiss="modal">
                                إلغاء
                              </button>
                             <form  
                                id="@item.Id"
                                class="text-danger delete-record"
                                method="post"
                                type="submit"
                                asp-action="Delete"
                                asp-route-id="@item.Id" 
                                >
                                <i onclick="return functionConfirm('@item.Id')" class="btn btn-danger bx bx-trash me-1"></i> </form>
                            </div>
                          </div>
                        </div>
                      </div>

                        }
                    }

                </tbody>
            </table>
    </div>
</div>
@section Scripts{
    
    <script>
        function functionConfirm(Id) {
            const swalWithBootstrapButtons = Swal.mixin({
                customClass: {
                    confirmButton: 'btn btn-success',
                    cancelButton: 'btn btn-danger'
                },
                buttonsStyling: false
            })

        swalWithBootstrapButtons.fire({
            title: 'هل انت متأكد من الحذف ؟',
            text: "سيتم حذف الرسالة بشكل نهائي  !",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonText: 'نعم  !',
            cancelButtonText: 'الغاء ',
            reverseButtons: true,
            timer: 10000
        }).then((result) => {
            if (result.isConfirmed) {
                $("#"+Id+"").submit();

                swalWithBootstrapButtons.fire({
                    title: 'تم الحذف !',
                    text :'تمت عملية الحذف بنجاح .',
                    icon: 'success',
                    timer:'200000'
                    }
                )
            } else if (
                /* Read more about handling dismissals below */
                result.dismiss === Swal.DismissReason.cancel
            ) {
                swalWithBootstrapButtons.fire(
                    ' تم إلغاء الحذف',
                    '',
                    'error'
                )
            }
        })
    }
</script>


<script>
    

    $(document).ready(function () {
       $('#dataTable').DataTable({
            responsive: true,
            "language": {
                "lengthMenu": "عرض _MENU_ سجلات  ",
                "info": "عرض صفحة _PAGE_ من _PAGES_",
                "infoEmpty": "  لاتوجد بيانات مطابقة للبحث",
                "infoFiltered": "(الصافي من  _MAX_ اجمالي الصفوف)",
                "search": "بحث",
            },


        });
    });
    
   
</script>


    
@*

<script>

    'use strict';

(function () {
  const popoverTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="popover"]'));
  const popoverList = popoverTriggerList.map(function (popoverTriggerEl) {
    return new bootstrap.Popover(popoverTriggerEl, { html: true, sanitize: false});
  });
})();



</script>*@


     }